# Mounts the directory to a container for debugging
FROM python:3.12.2-slim

# Set the working directory
WORKDIR /app

RUN apt update && apt install -y libpq-dev gcc

# Ensure pip is up-to-date
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the application
CMD ["python", "main.py"]
