name: Test build

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t parquet-export:pr-${{ github.event.pull_request.number }} .
